name = "road"
compatibility_date = "2023-12-01"

main = "src/app.ts"

[site]
bucket = "./src/assets"

[[kv_namespaces]]
binding = "road"
id = "5d7b8ab419fb4747a35963e2db105384"
preview_id = "fe42061ce3834ce3b0e704c5679bcbea"
